#ifndef __UTIl2_PUBLIC_DOMAIN_MERSENNE_TWISTER_ENGINE_VERSION2_2014_11_10_DEFINITION_HEADER__
#define __UTIl2_PUBLIC_DOMAIN_MERSENNE_TWISTER_ENGINE_VERSION2_2014_11_10_DEFINITION_HEADER__
#include "util2_extern.h"
#include "util2_api.h"
#include "util2/C/base_type.h"


UTIL2_EXTERNC_DECL_BEGIN

extern const u8 util2_mt19937ii_keyBufferLength;
typedef u32 util2_namespace_MT19937IIDefaultKeyBufferType[8];
typedef util2_namespace_MT19937IIDefaultKeyBufferType util2_mt19937ii_keyBuffer_t;


/* 
    Initialize the RNG with a default function.
    In particular, it generated 8 unique Pseudo Random int32_t's
    using stdlibs' rand()
    Use When:
        you don't care about the seed/reproducibility of the numbers
*/
void UTIL2_API util2_initializeMersenneTwister19937Ver2_FixedDefault();


/* 
    Initialize the RNG with a seed previously generated by the library (primarily),
    This doesn't stop you from defining the keyBuffer_t yourself and passing it here.
    Use When:
        you want to use a seed already generated (i.e from a debug session) 
        OR you need reproducible results 
*/
void UTIL2_API util2_initializeMersenneTwister19937Ver2_ExistingKeyBuffer(
    util2_mt19937ii_keyBuffer_t const* buf
);

void UTIL2_API util2_getMersenneTwister19937Ver2_KeyBuffer(
    util2_mt19937ii_keyBuffer_t* toSet
);


/* 
    Initialize The RNG with a predefined array of uint32_t's
    Use when:
        If you care about the seed and may want to control reproducibility
    [NOTE]: keyBufLengths' range is [0, 624]
    [NOTE]: if this function is used, then keyBuf is not stored.
*/
void UTIL2_API util2_initializeMersenneTwister19937Ver2_RandomKeyBuffer(
    u32 const* keyBuf, 
    u16        keyBufLength
);


u32    UTIL2_API util2_generate31BitUnsignedInt(void);
u32    UTIL2_API util2_generate32BitUnsignedInt(void);
double UTIL2_API util2_generateRealOnClosedInterval(void);
double UTIL2_API util2_generateRealOnHalfClosedInterval(void);
double UTIL2_API util2_generateRealOnOpenInterval(void);
double UTIL2_API util2_generateRealOnHalfClosedInterval53Bits(void);


UTIL2_EXTERNC_DECL_END


#endif /* __UTIl2_PUBLIC_DOMAIN_MERSENNE_TWISTER_ENGINE_VERSION2_2014_11_10_DEFINITION_HEADER__ */
